function makeMotion(overrides = {}) {
  return {
    inPoint: 0,
    outPoint: 1,
    baseSpeed: 1,
    bounceEnabled: false,
    bounceSpeed: 1,
    speedAmount: 0,
    speedThreshold: 0.12,
    speedMode: 'normal',
    speedSource: 'low',
    timelineAmount: 0,
    timelineThreshold: 0.2,
    timelineMode: 'pulse',
    timelineSource: 'low',
    scale: 1,
    scaleAmount: 0,
    scaleThreshold: 0.06,
    scaleMode: 'normal',
    scaleSource: 'low',
    ...overrides,
  }
}

function layerLinks(amount, speedAmount, source = 'low', mode = 'normal', threshold = 0.08) {
  return { amount, speedAmount, source, mode, threshold }
}

export const DEFAULT_SCENE_PRESETS = [
  {
    id: 'bass-driver',
    name: 'Bass Driver',
    description: 'Punchy low-end speed push with restrained FX.',
    settings: {
      bpm: 128,
      safeMode: false,
      audioSensitivity: 0.82,
      audioSmoothing: 0.42,
      audioNoiseFloor: 0.02,
      audioPreGain: 1.45,
      audioEq: { low: 1.25, mid: 0.95, high: 0.88 },
      masterFx: {
        glow: 0.24,
        strobe: 0.12,
        shake: 0.16,
        brightness: 1.08,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.44, threshold: 0.05, mode: 'normal', source: 'low' },
        strobe: { amount: 0.22, threshold: 0.16, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.35, threshold: 0.07, mode: 'normal', source: 'low' },
        brightness: { amount: 0.28, threshold: 0.04, mode: 'normal', source: 'sub' },
      },
      layerAudioLinks: {
        0: layerLinks(0.38, 0.58, 'sub', 'normal', 0.05),
        1: layerLinks(0.22, 0.36, 'low', 'normal', 0.08),
        2: layerLinks(0.16, 0.28, 'mid', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.56, speedSource: 'sub', scaleAmount: 0.26, scaleSource: 'low' }),
        1: makeMotion({ speedAmount: 0.32, speedSource: 'lowMid', scaleAmount: 0.18, scaleSource: 'mid' }),
        2: makeMotion({ speedAmount: 0.24, speedSource: 'mid', scaleAmount: 0.14, scaleSource: 'presence' }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: false,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'neon-pulse',
    name: 'Neon Pulse',
    description: 'Mid-band glow and brightness pumping for melodic sections.',
    settings: {
      bpm: 124,
      audioSensitivity: 0.78,
      audioSmoothing: 0.5,
      audioNoiseFloor: 0.018,
      audioPreGain: 1.3,
      audioEq: { low: 0.95, mid: 1.2, high: 1.1 },
      masterFx: {
        glow: 0.34,
        strobe: 0.08,
        shake: 0.1,
        brightness: 1.12,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.52, threshold: 0.03, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.15, threshold: 0.18, mode: 'pulse', source: 'high' },
        shake: { amount: 0.18, threshold: 0.1, mode: 'normal', source: 'lowMid' },
        brightness: { amount: 0.42, threshold: 0.03, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.32, 0.22, 'mid', 'normal', 0.06),
        1: layerLinks(0.3, 0.3, 'lowMid', 'normal', 0.07),
        2: layerLinks(0.26, 0.36, 'presence', 'normal', 0.08),
      },
      layerVideoMotion: {
        0: makeMotion({ scaleAmount: 0.24, scaleSource: 'mid', timelineAmount: 0.28, timelineSource: 'mid' }),
        1: makeMotion({ scaleAmount: 0.2, scaleSource: 'presence', timelineAmount: 0.34, timelineSource: 'lowMid' }),
        2: makeMotion({ speedAmount: 0.3, speedSource: 'mid', timelineAmount: 0.2, timelineSource: 'high' }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 60,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'glitch-arcade',
    name: 'Glitch Arcade',
    description: 'High-energy stutter style with bounce and pulse timeline jumps.',
    settings: {
      bpm: 140,
      audioSensitivity: 0.92,
      audioSmoothing: 0.36,
      audioNoiseFloor: 0.024,
      audioPreGain: 1.6,
      audioEq: { low: 1.15, mid: 1.08, high: 1.18 },
      masterFx: {
        glow: 0.2,
        strobe: 0.28,
        shake: 0.26,
        brightness: 1.04,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.34, threshold: 0.06, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.42, threshold: 0.12, mode: 'pulse', source: 'full' },
        shake: { amount: 0.46, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.2, threshold: 0.05, mode: 'invert', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.42, 0.68, 'full', 'pulse', 0.1),
        1: layerLinks(0.34, 0.62, 'high', 'pulse', 0.12),
        2: layerLinks(0.3, 0.58, 'mid', 'pulse', 0.11),
      },
      layerVideoMotion: {
        0: makeMotion({ bounceEnabled: true, bounceSpeed: 1.25, timelineAmount: 0.55, timelineMode: 'pulse', timelineSource: 'full', speedAmount: 0.62 }),
        1: makeMotion({ bounceEnabled: true, bounceSpeed: 1.18, timelineAmount: 0.48, timelineMode: 'pulse', timelineSource: 'high', speedAmount: 0.54 }),
        2: makeMotion({ bounceEnabled: true, bounceSpeed: 1.1, timelineAmount: 0.4, timelineMode: 'pulse', timelineSource: 'mid', speedAmount: 0.46 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'low',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 30,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'cinematic-flow',
    name: 'Cinematic Flow',
    description: 'Smoother long-form movement with gentle audio coupling.',
    settings: {
      bpm: 110,
      audioSensitivity: 0.68,
      audioSmoothing: 0.66,
      audioNoiseFloor: 0.015,
      audioPreGain: 1.2,
      audioEq: { low: 1.02, mid: 1, high: 0.92 },
      masterFx: {
        glow: 0.18,
        strobe: 0.04,
        shake: 0.06,
        brightness: 1.14,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.26, threshold: 0.03, mode: 'normal', source: 'lowMid' },
        strobe: { amount: 0.06, threshold: 0.24, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.1, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.3, threshold: 0.03, mode: 'normal', source: 'lowMid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.2, 0.24, 'lowMid', 'normal', 0.07),
        1: layerLinks(0.18, 0.2, 'mid', 'normal', 0.07),
        2: layerLinks(0.14, 0.16, 'presence', 'normal', 0.08),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.2, timelineAmount: 0.14, scaleAmount: 0.12, scaleSource: 'lowMid' }),
        1: makeMotion({ speedAmount: 0.16, timelineAmount: 0.1, scaleAmount: 0.1, scaleSource: 'mid' }),
        2: makeMotion({ speedAmount: 0.14, timelineAmount: 0.08, scaleAmount: 0.08, scaleSource: 'presence' }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: false,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 120,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'drop-hunter',
    name: 'Drop Hunter',
    description: 'Aggressive drop detection with heavy transient response.',
    settings: {
      bpm: 150,
      audioSensitivity: 0.96,
      audioSmoothing: 0.3,
      audioNoiseFloor: 0.03,
      audioPreGain: 1.8,
      audioEq: { low: 1.3, mid: 1.02, high: 1.05 },
      masterFx: {
        glow: 0.26,
        strobe: 0.3,
        shake: 0.32,
        brightness: 1.02,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.36, threshold: 0.06, mode: 'normal', source: 'sub' },
        strobe: { amount: 0.55, threshold: 0.1, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.58, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.24, threshold: 0.06, mode: 'pulse', source: 'full' },
      },
      layerAudioLinks: {
        0: layerLinks(0.5, 0.8, 'sub', 'pulse', 0.08),
        1: layerLinks(0.42, 0.66, 'low', 'pulse', 0.09),
        2: layerLinks(0.34, 0.54, 'full', 'pulse', 0.1),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.72, speedSource: 'sub', timelineAmount: 0.6, timelineMode: 'pulse', scaleAmount: 0.32 }),
        1: makeMotion({ speedAmount: 0.6, speedSource: 'low', timelineAmount: 0.52, timelineMode: 'pulse', scaleAmount: 0.26 }),
        2: makeMotion({ speedAmount: 0.48, speedSource: 'full', timelineAmount: 0.44, timelineMode: 'pulse', scaleAmount: 0.2 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'low',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 20,
      beatSyncEnabled: true,
    },
  },
]
