function makeMotion(overrides = {}) {
  return {
    inPoint: 0,
    outPoint: 1,
    baseSpeed: 1,
    bounceEnabled: false,
    bounceSpeed: 1,
    speedAmount: 0,
    speedThreshold: 0.12,
    speedMode: 'normal',
    speedSource: 'low',
    timelineAmount: 0,
    timelineThreshold: 0.2,
    timelineMode: 'pulse',
    timelineSource: 'low',
    scale: 1,
    scaleAmount: 0,
    scaleThreshold: 0.06,
    scaleMode: 'normal',
    scaleSource: 'low',
    ...overrides,
  }
}

function layerLinks(amount, speedAmount, source = 'low', mode = 'normal', threshold = 0.08) {
  return { amount, speedAmount, source, mode, threshold }
}

export const DEFAULT_SCENE_PRESETS = [
  {
    id: 'bass-driver',
    name: 'Bass Driver',
    description: 'Punchy low-end speed push with restrained FX.',
    settings: {
      bpm: 128,
      safeMode: false,
      audioSensitivity: 0.82,
      audioSmoothing: 0.42,
      audioNoiseFloor: 0.02,
      audioPreGain: 1.45,
      audioEq: { low: 1.25, mid: 0.95, high: 0.88 },
      masterFx: {
        glow: 0.24,
        strobe: 0.12,
        shake: 0.16,
        brightness: 1.08,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.44, threshold: 0.05, mode: 'normal', source: 'low' },
        strobe: { amount: 0.22, threshold: 0.16, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.35, threshold: 0.07, mode: 'normal', source: 'low' },
        brightness: { amount: 0.28, threshold: 0.04, mode: 'normal', source: 'sub' },
      },
      layerAudioLinks: {
        0: layerLinks(0.38, 0.58, 'sub', 'normal', 0.05),
        1: layerLinks(0.22, 0.36, 'low', 'normal', 0.08),
        2: layerLinks(0.16, 0.28, 'mid', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.56, speedSource: 'sub', scaleAmount: 0.26, scaleSource: 'low' }),
        1: makeMotion({ speedAmount: 0.32, speedSource: 'lowMid', scaleAmount: 0.18, scaleSource: 'mid' }),
        2: makeMotion({ speedAmount: 0.24, speedSource: 'mid', scaleAmount: 0.14, scaleSource: 'presence' }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: false,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'neon-pulse',
    name: 'Neon Pulse',
    description: 'Mid-band glow and brightness pumping for melodic sections.',
    settings: {
      bpm: 124,
      audioSensitivity: 0.78,
      audioSmoothing: 0.5,
      audioNoiseFloor: 0.018,
      audioPreGain: 1.3,
      audioEq: { low: 0.95, mid: 1.2, high: 1.1 },
      masterFx: {
        glow: 0.34,
        strobe: 0.08,
        shake: 0.1,
        brightness: 1.12,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.52, threshold: 0.03, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.15, threshold: 0.18, mode: 'pulse', source: 'high' },
        shake: { amount: 0.18, threshold: 0.1, mode: 'normal', source: 'lowMid' },
        brightness: { amount: 0.42, threshold: 0.03, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.32, 0.22, 'mid', 'normal', 0.06),
        1: layerLinks(0.3, 0.3, 'lowMid', 'normal', 0.07),
        2: layerLinks(0.26, 0.36, 'presence', 'normal', 0.08),
      },
      layerVideoMotion: {
        0: makeMotion({ scaleAmount: 0.24, scaleSource: 'mid', timelineAmount: 0.28, timelineSource: 'mid' }),
        1: makeMotion({ scaleAmount: 0.2, scaleSource: 'presence', timelineAmount: 0.34, timelineSource: 'lowMid' }),
        2: makeMotion({ speedAmount: 0.3, speedSource: 'mid', timelineAmount: 0.2, timelineSource: 'high' }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 60,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'glitch-arcade',
    name: 'Glitch Arcade',
    description: 'High-energy stutter style with bounce and pulse timeline jumps.',
    settings: {
      bpm: 140,
      audioSensitivity: 0.92,
      audioSmoothing: 0.36,
      audioNoiseFloor: 0.024,
      audioPreGain: 1.6,
      audioEq: { low: 1.15, mid: 1.08, high: 1.18 },
      masterFx: {
        glow: 0.2,
        strobe: 0.28,
        shake: 0.26,
        brightness: 1.04,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.34, threshold: 0.06, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.42, threshold: 0.12, mode: 'pulse', source: 'full' },
        shake: { amount: 0.46, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.2, threshold: 0.05, mode: 'invert', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.42, 0.68, 'full', 'pulse', 0.1),
        1: layerLinks(0.34, 0.62, 'high', 'pulse', 0.12),
        2: layerLinks(0.3, 0.58, 'mid', 'pulse', 0.11),
      },
      layerVideoMotion: {
        0: makeMotion({ bounceEnabled: true, bounceSpeed: 1.25, timelineAmount: 0.55, timelineMode: 'pulse', timelineSource: 'full', speedAmount: 0.62 }),
        1: makeMotion({ bounceEnabled: true, bounceSpeed: 1.18, timelineAmount: 0.48, timelineMode: 'pulse', timelineSource: 'high', speedAmount: 0.54 }),
        2: makeMotion({ bounceEnabled: true, bounceSpeed: 1.1, timelineAmount: 0.4, timelineMode: 'pulse', timelineSource: 'mid', speedAmount: 0.46 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'low',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 30,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'cinematic-flow',
    name: 'Cinematic Flow',
    description: 'Smoother long-form movement with gentle audio coupling.',
    settings: {
      bpm: 110,
      audioSensitivity: 0.68,
      audioSmoothing: 0.66,
      audioNoiseFloor: 0.015,
      audioPreGain: 1.2,
      audioEq: { low: 1.02, mid: 1, high: 0.92 },
      masterFx: {
        glow: 0.18,
        strobe: 0.04,
        shake: 0.06,
        brightness: 1.14,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.26, threshold: 0.03, mode: 'normal', source: 'lowMid' },
        strobe: { amount: 0.06, threshold: 0.24, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.1, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.3, threshold: 0.03, mode: 'normal', source: 'lowMid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.2, 0.24, 'lowMid', 'normal', 0.07),
        1: layerLinks(0.18, 0.2, 'mid', 'normal', 0.07),
        2: layerLinks(0.14, 0.16, 'presence', 'normal', 0.08),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.2, timelineAmount: 0.14, scaleAmount: 0.12, scaleSource: 'lowMid' }),
        1: makeMotion({ speedAmount: 0.16, timelineAmount: 0.1, scaleAmount: 0.1, scaleSource: 'mid' }),
        2: makeMotion({ speedAmount: 0.14, timelineAmount: 0.08, scaleAmount: 0.08, scaleSource: 'presence' }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: false,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 120,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'drop-hunter',
    name: 'Drop Hunter',
    description: 'Aggressive drop detection with heavy transient response.',
    settings: {
      bpm: 150,
      audioSensitivity: 0.96,
      audioSmoothing: 0.3,
      audioNoiseFloor: 0.03,
      audioPreGain: 1.8,
      audioEq: { low: 1.3, mid: 1.02, high: 1.05 },
      masterFx: {
        glow: 0.26,
        strobe: 0.3,
        shake: 0.32,
        brightness: 1.02,
        kaleido: 0,
        kaleidoSegments: 6,
        kaleidoSpin: 0,
        kaleidoAudio: 0.5,
        kaleidoSource: 'mid',
      },
      audioFxLinks: {
        glow: { amount: 0.36, threshold: 0.06, mode: 'normal', source: 'sub' },
        strobe: { amount: 0.55, threshold: 0.1, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.58, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.24, threshold: 0.06, mode: 'pulse', source: 'full' },
      },
      layerAudioLinks: {
        0: layerLinks(0.5, 0.8, 'sub', 'pulse', 0.08),
        1: layerLinks(0.42, 0.66, 'low', 'pulse', 0.09),
        2: layerLinks(0.34, 0.54, 'full', 'pulse', 0.1),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.72, speedSource: 'sub', timelineAmount: 0.6, timelineMode: 'pulse', scaleAmount: 0.32 }),
        1: makeMotion({ speedAmount: 0.6, speedSource: 'low', timelineAmount: 0.52, timelineMode: 'pulse', scaleAmount: 0.26 }),
        2: makeMotion({ speedAmount: 0.48, speedSource: 'full', timelineAmount: 0.44, timelineMode: 'pulse', scaleAmount: 0.2 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'low',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 20,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'sub-pressure',
    name: 'Sub Pressure',
    description: 'Heavy sub-driven pumping with tight pulse gates.',
    settings: {
      bpm: 136,
      audioSensitivity: 0.88,
      audioSmoothing: 0.4,
      audioNoiseFloor: 0.024,
      audioPreGain: 1.55,
      audioEq: { low: 1.35, mid: 0.9, high: 0.84 },
      masterFx: { glow: 0.22, strobe: 0.18, shake: 0.24, brightness: 1.06, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.38, threshold: 0.06, mode: 'normal', source: 'sub' },
        strobe: { amount: 0.34, threshold: 0.13, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.42, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.18, threshold: 0.05, mode: 'normal', source: 'sub' },
      },
      layerAudioLinks: {
        0: layerLinks(0.46, 0.7, 'sub', 'pulse', 0.08),
        1: layerLinks(0.32, 0.52, 'low', 'pulse', 0.09),
        2: layerLinks(0.24, 0.4, 'lowMid', 'normal', 0.1),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.66, speedSource: 'sub', timelineAmount: 0.48, timelineMode: 'pulse', scaleAmount: 0.3 }),
        1: makeMotion({ speedAmount: 0.52, speedSource: 'low', timelineAmount: 0.36, timelineMode: 'pulse', scaleAmount: 0.22 }),
        2: makeMotion({ speedAmount: 0.34, speedSource: 'lowMid', timelineAmount: 0.24, scaleAmount: 0.16 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: false,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'prism-drive',
    name: 'Prism Drive',
    description: 'Bright high-band accents with sharp rhythmic scaling.',
    settings: {
      bpm: 132,
      audioSensitivity: 0.8,
      audioSmoothing: 0.44,
      audioNoiseFloor: 0.02,
      audioPreGain: 1.34,
      audioEq: { low: 0.92, mid: 1.12, high: 1.28 },
      masterFx: { glow: 0.36, strobe: 0.12, shake: 0.14, brightness: 1.12, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.5, threshold: 0.03, mode: 'normal', source: 'high' },
        strobe: { amount: 0.22, threshold: 0.16, mode: 'pulse', source: 'presence' },
        shake: { amount: 0.2, threshold: 0.09, mode: 'normal', source: 'mid' },
        brightness: { amount: 0.44, threshold: 0.04, mode: 'normal', source: 'high' },
      },
      layerAudioLinks: {
        0: layerLinks(0.28, 0.34, 'presence', 'normal', 0.07),
        1: layerLinks(0.3, 0.38, 'high', 'normal', 0.08),
        2: layerLinks(0.24, 0.3, 'mid', 'normal', 0.08),
      },
      layerVideoMotion: {
        0: makeMotion({ scaleAmount: 0.28, scaleSource: 'high', timelineAmount: 0.24, timelineSource: 'presence' }),
        1: makeMotion({ scaleAmount: 0.22, scaleSource: 'presence', speedAmount: 0.34, speedSource: 'high' }),
        2: makeMotion({ scaleAmount: 0.18, scaleSource: 'mid', speedAmount: 0.22, speedSource: 'mid' }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 45,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'velvet-drift',
    name: 'Velvet Drift',
    description: 'Low-intensity ambient glide with soft movement.',
    settings: {
      bpm: 98,
      audioSensitivity: 0.62,
      audioSmoothing: 0.72,
      audioNoiseFloor: 0.012,
      audioPreGain: 1.1,
      audioEq: { low: 1, mid: 0.96, high: 0.86 },
      masterFx: { glow: 0.14, strobe: 0.02, shake: 0.04, brightness: 1.18, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.2, threshold: 0.02, mode: 'normal', source: 'lowMid' },
        strobe: { amount: 0.02, threshold: 0.28, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.06, threshold: 0.12, mode: 'normal', source: 'low' },
        brightness: { amount: 0.24, threshold: 0.02, mode: 'normal', source: 'lowMid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.12, 0.14, 'lowMid', 'normal', 0.08),
        1: layerLinks(0.1, 0.12, 'mid', 'normal', 0.09),
        2: layerLinks(0.08, 0.1, 'presence', 'normal', 0.1),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.12, timelineAmount: 0.06, scaleAmount: 0.08, scaleSource: 'lowMid' }),
        1: makeMotion({ speedAmount: 0.1, timelineAmount: 0.05, scaleAmount: 0.06, scaleSource: 'mid' }),
        2: makeMotion({ speedAmount: 0.08, timelineAmount: 0.04, scaleAmount: 0.05, scaleSource: 'presence' }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: false,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 150,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'radar-scan',
    name: 'Radar Scan',
    description: 'Pulsed timeline sweeps with periodic burst accents.',
    settings: {
      bpm: 118,
      audioSensitivity: 0.76,
      audioSmoothing: 0.48,
      audioNoiseFloor: 0.018,
      audioPreGain: 1.26,
      audioEq: { low: 1.08, mid: 1.05, high: 0.98 },
      masterFx: { glow: 0.28, strobe: 0.1, shake: 0.12, brightness: 1.1, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.34, threshold: 0.04, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.18, threshold: 0.17, mode: 'pulse', source: 'full' },
        shake: { amount: 0.22, threshold: 0.08, mode: 'normal', source: 'lowMid' },
        brightness: { amount: 0.3, threshold: 0.03, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.26, 0.32, 'full', 'pulse', 0.1),
        1: layerLinks(0.24, 0.3, 'mid', 'pulse', 0.1),
        2: layerLinks(0.2, 0.24, 'presence', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ timelineAmount: 0.42, timelineMode: 'pulse', timelineSource: 'full', speedAmount: 0.28 }),
        1: makeMotion({ timelineAmount: 0.34, timelineMode: 'pulse', timelineSource: 'mid', speedAmount: 0.22 }),
        2: makeMotion({ timelineAmount: 0.24, timelineMode: 'pulse', timelineSource: 'presence', speedAmount: 0.18 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'high',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 75,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'metal-surge',
    name: 'Metal Surge',
    description: 'Fast transient aggression tuned for dense mixes.',
    settings: {
      bpm: 168,
      audioSensitivity: 0.95,
      audioSmoothing: 0.28,
      audioNoiseFloor: 0.03,
      audioPreGain: 1.9,
      audioEq: { low: 1.18, mid: 1.2, high: 1.12 },
      masterFx: { glow: 0.22, strobe: 0.34, shake: 0.38, brightness: 1.02, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.32, threshold: 0.06, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.62, threshold: 0.09, mode: 'pulse', source: 'full' },
        shake: { amount: 0.66, threshold: 0.07, mode: 'normal', source: 'full' },
        brightness: { amount: 0.16, threshold: 0.08, mode: 'invert', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.52, 0.84, 'full', 'pulse', 0.09),
        1: layerLinks(0.44, 0.72, 'mid', 'pulse', 0.1),
        2: layerLinks(0.36, 0.6, 'high', 'pulse', 0.11),
      },
      layerVideoMotion: {
        0: makeMotion({ bounceEnabled: true, bounceSpeed: 1.3, speedAmount: 0.78, timelineAmount: 0.58, timelineMode: 'pulse', scaleAmount: 0.34 }),
        1: makeMotion({ bounceEnabled: true, bounceSpeed: 1.2, speedAmount: 0.66, timelineAmount: 0.5, timelineMode: 'pulse', scaleAmount: 0.28 }),
        2: makeMotion({ bounceEnabled: true, bounceSpeed: 1.14, speedAmount: 0.54, timelineAmount: 0.42, timelineMode: 'pulse', scaleAmount: 0.22 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'low',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 15,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'afterglow',
    name: 'Afterglow',
    description: 'Warm post-drop recovery with soft bloom and motion.',
    settings: {
      bpm: 116,
      audioSensitivity: 0.7,
      audioSmoothing: 0.6,
      audioNoiseFloor: 0.017,
      audioPreGain: 1.18,
      audioEq: { low: 1.04, mid: 1.08, high: 0.94 },
      masterFx: { glow: 0.3, strobe: 0.04, shake: 0.08, brightness: 1.16, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.4, threshold: 0.03, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.06, threshold: 0.22, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.12, threshold: 0.09, mode: 'normal', source: 'lowMid' },
        brightness: { amount: 0.36, threshold: 0.03, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.24, 0.24, 'mid', 'normal', 0.07),
        1: layerLinks(0.2, 0.2, 'lowMid', 'normal', 0.08),
        2: layerLinks(0.16, 0.16, 'presence', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ scaleAmount: 0.2, scaleSource: 'mid', speedAmount: 0.2 }),
        1: makeMotion({ scaleAmount: 0.16, scaleSource: 'lowMid', speedAmount: 0.16 }),
        2: makeMotion({ scaleAmount: 0.12, scaleSource: 'presence', speedAmount: 0.12 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 90,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'vortex-pop',
    name: 'Vortex Pop',
    description: 'Spiky groove with animated scale and timeline pops.',
    settings: {
      bpm: 126,
      audioSensitivity: 0.84,
      audioSmoothing: 0.4,
      audioNoiseFloor: 0.022,
      audioPreGain: 1.42,
      audioEq: { low: 1.08, mid: 1.14, high: 1.06 },
      masterFx: { glow: 0.26, strobe: 0.16, shake: 0.2, brightness: 1.1, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.42, threshold: 0.04, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.24, threshold: 0.14, mode: 'pulse', source: 'high' },
        shake: { amount: 0.3, threshold: 0.08, mode: 'normal', source: 'lowMid' },
        brightness: { amount: 0.28, threshold: 0.04, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.34, 0.42, 'mid', 'normal', 0.07),
        1: layerLinks(0.28, 0.36, 'high', 'pulse', 0.09),
        2: layerLinks(0.24, 0.3, 'lowMid', 'normal', 0.08),
      },
      layerVideoMotion: {
        0: makeMotion({ timelineAmount: 0.36, timelineMode: 'pulse', timelineSource: 'mid', scaleAmount: 0.24 }),
        1: makeMotion({ timelineAmount: 0.32, timelineMode: 'pulse', timelineSource: 'high', scaleAmount: 0.2 }),
        2: makeMotion({ timelineAmount: 0.24, timelineMode: 'normal', timelineSource: 'lowMid', scaleAmount: 0.16 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 50,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'midnight-grid',
    name: 'Midnight Grid',
    description: 'Tight controlled pulses for techno-style layering.',
    settings: {
      bpm: 128,
      audioSensitivity: 0.74,
      audioSmoothing: 0.54,
      audioNoiseFloor: 0.02,
      audioPreGain: 1.24,
      audioEq: { low: 1.06, mid: 1.04, high: 0.98 },
      masterFx: { glow: 0.2, strobe: 0.08, shake: 0.12, brightness: 1.08, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.3, threshold: 0.04, mode: 'normal', source: 'lowMid' },
        strobe: { amount: 0.14, threshold: 0.16, mode: 'pulse', source: 'mid' },
        shake: { amount: 0.2, threshold: 0.09, mode: 'normal', source: 'low' },
        brightness: { amount: 0.24, threshold: 0.04, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.26, 0.28, 'lowMid', 'normal', 0.08),
        1: layerLinks(0.22, 0.24, 'mid', 'normal', 0.08),
        2: layerLinks(0.18, 0.22, 'presence', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.24, timelineAmount: 0.2, scaleAmount: 0.14 }),
        1: makeMotion({ speedAmount: 0.2, timelineAmount: 0.16, scaleAmount: 0.12 }),
        2: makeMotion({ speedAmount: 0.16, timelineAmount: 0.14, scaleAmount: 0.1 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: false,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 80,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'plasma-rush',
    name: 'Plasma Rush',
    description: 'Fast rolling energy with broad-spectrum response.',
    settings: {
      bpm: 144,
      audioSensitivity: 0.9,
      audioSmoothing: 0.34,
      audioNoiseFloor: 0.026,
      audioPreGain: 1.66,
      audioEq: { low: 1.16, mid: 1.1, high: 1.12 },
      masterFx: { glow: 0.3, strobe: 0.24, shake: 0.28, brightness: 1.06, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.44, threshold: 0.05, mode: 'normal', source: 'full' },
        strobe: { amount: 0.3, threshold: 0.12, mode: 'pulse', source: 'full' },
        shake: { amount: 0.46, threshold: 0.08, mode: 'normal', source: 'full' },
        brightness: { amount: 0.26, threshold: 0.05, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.4, 0.64, 'full', 'normal', 0.08),
        1: layerLinks(0.32, 0.52, 'mid', 'normal', 0.09),
        2: layerLinks(0.28, 0.46, 'high', 'normal', 0.1),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.62, timelineAmount: 0.4, scaleAmount: 0.3 }),
        1: makeMotion({ speedAmount: 0.5, timelineAmount: 0.34, scaleAmount: 0.24 }),
        2: makeMotion({ speedAmount: 0.42, timelineAmount: 0.28, scaleAmount: 0.2 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 25,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'echo-chamber',
    name: 'Echo Chamber',
    description: 'Breathing midrange movements for atmospheric tracks.',
    settings: {
      bpm: 112,
      audioSensitivity: 0.66,
      audioSmoothing: 0.64,
      audioNoiseFloor: 0.016,
      audioPreGain: 1.15,
      audioEq: { low: 0.98, mid: 1.14, high: 0.9 },
      masterFx: { glow: 0.26, strobe: 0.03, shake: 0.08, brightness: 1.15, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.34, threshold: 0.03, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.04, threshold: 0.25, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.1, threshold: 0.09, mode: 'normal', source: 'lowMid' },
        brightness: { amount: 0.32, threshold: 0.03, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.2, 0.2, 'mid', 'normal', 0.07),
        1: layerLinks(0.18, 0.16, 'lowMid', 'normal', 0.08),
        2: layerLinks(0.16, 0.14, 'presence', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ scaleAmount: 0.18, scaleSource: 'mid', speedAmount: 0.16 }),
        1: makeMotion({ scaleAmount: 0.14, scaleSource: 'lowMid', speedAmount: 0.14 }),
        2: makeMotion({ scaleAmount: 0.1, scaleSource: 'presence', speedAmount: 0.1 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: false,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 110,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'pulse-lab',
    name: 'Pulse Lab',
    description: 'Experimental pulse modes on all channels.',
    settings: {
      bpm: 130,
      audioSensitivity: 0.86,
      audioSmoothing: 0.38,
      audioNoiseFloor: 0.022,
      audioPreGain: 1.5,
      audioEq: { low: 1.1, mid: 1.08, high: 1.08 },
      masterFx: { glow: 0.24, strobe: 0.2, shake: 0.22, brightness: 1.08, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.46, threshold: 0.05, mode: 'pulse', source: 'mid' },
        strobe: { amount: 0.28, threshold: 0.14, mode: 'pulse', source: 'full' },
        shake: { amount: 0.36, threshold: 0.1, mode: 'pulse', source: 'low' },
        brightness: { amount: 0.24, threshold: 0.08, mode: 'pulse', source: 'high' },
      },
      layerAudioLinks: {
        0: layerLinks(0.32, 0.52, 'full', 'pulse', 0.1),
        1: layerLinks(0.28, 0.44, 'mid', 'pulse', 0.1),
        2: layerLinks(0.24, 0.38, 'high', 'pulse', 0.11),
      },
      layerVideoMotion: {
        0: makeMotion({ timelineAmount: 0.5, timelineMode: 'pulse', timelineSource: 'full', speedAmount: 0.46 }),
        1: makeMotion({ timelineAmount: 0.42, timelineMode: 'pulse', timelineSource: 'mid', speedAmount: 0.38 }),
        2: makeMotion({ timelineAmount: 0.34, timelineMode: 'pulse', timelineSource: 'high', speedAmount: 0.3 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 40,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'sunrise-lift',
    name: 'Sunrise Lift',
    description: 'Gradual uplifting build with less strobe and more glow.',
    settings: {
      bpm: 122,
      audioSensitivity: 0.72,
      audioSmoothing: 0.58,
      audioNoiseFloor: 0.017,
      audioPreGain: 1.22,
      audioEq: { low: 0.96, mid: 1.12, high: 1.02 },
      masterFx: { glow: 0.34, strobe: 0.05, shake: 0.1, brightness: 1.16, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.48, threshold: 0.03, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.08, threshold: 0.22, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.14, threshold: 0.09, mode: 'normal', source: 'low' },
        brightness: { amount: 0.38, threshold: 0.03, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.24, 0.24, 'mid', 'normal', 0.07),
        1: layerLinks(0.2, 0.2, 'lowMid', 'normal', 0.08),
        2: layerLinks(0.16, 0.16, 'presence', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ scaleAmount: 0.22, speedAmount: 0.22, timelineAmount: 0.16 }),
        1: makeMotion({ scaleAmount: 0.18, speedAmount: 0.18, timelineAmount: 0.14 }),
        2: makeMotion({ scaleAmount: 0.14, speedAmount: 0.14, timelineAmount: 0.12 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 70,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'tunnel-chase',
    name: 'Tunnel Chase',
    description: 'Forward-driving speed emphasis with fast layer reactions.',
    settings: {
      bpm: 146,
      audioSensitivity: 0.9,
      audioSmoothing: 0.34,
      audioNoiseFloor: 0.026,
      audioPreGain: 1.7,
      audioEq: { low: 1.2, mid: 1.06, high: 1.06 },
      masterFx: { glow: 0.22, strobe: 0.2, shake: 0.3, brightness: 1.05, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.34, threshold: 0.05, mode: 'normal', source: 'low' },
        strobe: { amount: 0.26, threshold: 0.13, mode: 'pulse', source: 'full' },
        shake: { amount: 0.52, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.2, threshold: 0.06, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.38, 0.74, 'low', 'normal', 0.07),
        1: layerLinks(0.32, 0.62, 'lowMid', 'normal', 0.08),
        2: layerLinks(0.26, 0.5, 'mid', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.76, speedSource: 'low', timelineAmount: 0.36, scaleAmount: 0.26 }),
        1: makeMotion({ speedAmount: 0.62, speedSource: 'lowMid', timelineAmount: 0.3, scaleAmount: 0.22 }),
        2: makeMotion({ speedAmount: 0.5, speedSource: 'mid', timelineAmount: 0.24, scaleAmount: 0.18 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 25,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'hardcut-hype',
    name: 'Hardcut Hype',
    description: 'Quick-cut performance mode for short energetic sets.',
    settings: {
      bpm: 154,
      audioSensitivity: 0.94,
      audioSmoothing: 0.3,
      audioNoiseFloor: 0.03,
      audioPreGain: 1.78,
      audioEq: { low: 1.22, mid: 1.1, high: 1.08 },
      masterFx: { glow: 0.2, strobe: 0.32, shake: 0.34, brightness: 1.04, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.32, threshold: 0.06, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.58, threshold: 0.1, mode: 'pulse', source: 'full' },
        shake: { amount: 0.6, threshold: 0.08, mode: 'normal', source: 'full' },
        brightness: { amount: 0.16, threshold: 0.08, mode: 'invert', source: 'high' },
      },
      layerAudioLinks: {
        0: layerLinks(0.48, 0.8, 'full', 'pulse', 0.09),
        1: layerLinks(0.4, 0.66, 'mid', 'pulse', 0.1),
        2: layerLinks(0.34, 0.56, 'high', 'pulse', 0.11),
      },
      layerVideoMotion: {
        0: makeMotion({ bounceEnabled: true, bounceSpeed: 1.24, speedAmount: 0.74, timelineAmount: 0.56, timelineMode: 'pulse', scaleAmount: 0.3 }),
        1: makeMotion({ bounceEnabled: true, bounceSpeed: 1.18, speedAmount: 0.62, timelineAmount: 0.48, timelineMode: 'pulse', scaleAmount: 0.24 }),
        2: makeMotion({ bounceEnabled: true, bounceSpeed: 1.12, speedAmount: 0.5, timelineAmount: 0.4, timelineMode: 'pulse', scaleAmount: 0.2 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'low',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 18,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'skyline-bounce',
    name: 'Skyline Bounce',
    description: 'Upbeat bouncy profile with balanced full-range response.',
    settings: {
      bpm: 128,
      audioSensitivity: 0.82,
      audioSmoothing: 0.44,
      audioNoiseFloor: 0.021,
      audioPreGain: 1.38,
      audioEq: { low: 1.08, mid: 1.06, high: 1.02 },
      masterFx: { glow: 0.28, strobe: 0.14, shake: 0.2, brightness: 1.1, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.4, threshold: 0.04, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.2, threshold: 0.15, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.3, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.26, threshold: 0.04, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.32, 0.48, 'low', 'normal', 0.07),
        1: layerLinks(0.28, 0.4, 'mid', 'normal', 0.08),
        2: layerLinks(0.24, 0.34, 'presence', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ bounceEnabled: true, bounceSpeed: 1.14, speedAmount: 0.48, timelineAmount: 0.28, scaleAmount: 0.22 }),
        1: makeMotion({ bounceEnabled: true, bounceSpeed: 1.1, speedAmount: 0.4, timelineAmount: 0.24, scaleAmount: 0.18 }),
        2: makeMotion({ bounceEnabled: true, bounceSpeed: 1.06, speedAmount: 0.32, timelineAmount: 0.2, scaleAmount: 0.14 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 55,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'aurora-bloom',
    name: 'Aurora Bloom',
    description: 'Color-rich slow bloom with evolving motion texture.',
    settings: {
      bpm: 104,
      audioSensitivity: 0.64,
      audioSmoothing: 0.7,
      audioNoiseFloor: 0.014,
      audioPreGain: 1.12,
      audioEq: { low: 0.94, mid: 1.1, high: 1.04 },
      masterFx: { glow: 0.38, strobe: 0.02, shake: 0.05, brightness: 1.2, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.5, threshold: 0.02, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.03, threshold: 0.28, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.08, threshold: 0.1, mode: 'normal', source: 'lowMid' },
        brightness: { amount: 0.4, threshold: 0.02, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.18, 0.18, 'mid', 'normal', 0.07),
        1: layerLinks(0.16, 0.16, 'lowMid', 'normal', 0.08),
        2: layerLinks(0.14, 0.14, 'presence', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ scaleAmount: 0.16, speedAmount: 0.12, timelineAmount: 0.1 }),
        1: makeMotion({ scaleAmount: 0.14, speedAmount: 0.1, timelineAmount: 0.08 }),
        2: makeMotion({ scaleAmount: 0.12, speedAmount: 0.08, timelineAmount: 0.06 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 140,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'mono-crush',
    name: 'Mono Crush',
    description: 'Minimalist high-contrast rhythm profile.',
    settings: {
      bpm: 138,
      audioSensitivity: 0.88,
      audioSmoothing: 0.36,
      audioNoiseFloor: 0.026,
      audioPreGain: 1.6,
      audioEq: { low: 1.2, mid: 1.0, high: 0.9 },
      masterFx: { glow: 0.16, strobe: 0.26, shake: 0.28, brightness: 1.0, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.24, threshold: 0.06, mode: 'normal', source: 'low' },
        strobe: { amount: 0.46, threshold: 0.11, mode: 'pulse', source: 'full' },
        shake: { amount: 0.5, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.1, threshold: 0.08, mode: 'invert', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.36, 0.64, 'low', 'pulse', 0.09),
        1: layerLinks(0.3, 0.52, 'mid', 'pulse', 0.1),
        2: layerLinks(0.24, 0.42, 'full', 'pulse', 0.11),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.62, timelineAmount: 0.46, timelineMode: 'pulse', scaleAmount: 0.24 }),
        1: makeMotion({ speedAmount: 0.5, timelineAmount: 0.36, timelineMode: 'pulse', scaleAmount: 0.2 }),
        2: makeMotion({ speedAmount: 0.4, timelineAmount: 0.28, timelineMode: 'pulse', scaleAmount: 0.16 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: false,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 35,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'hybrid-pop',
    name: 'Hybrid Pop',
    description: 'Balanced all-purpose scene for mixed genre sets.',
    settings: {
      bpm: 126,
      audioSensitivity: 0.8,
      audioSmoothing: 0.48,
      audioNoiseFloor: 0.02,
      audioPreGain: 1.35,
      audioEq: { low: 1.06, mid: 1.08, high: 1.02 },
      masterFx: { glow: 0.28, strobe: 0.1, shake: 0.16, brightness: 1.1, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.38, threshold: 0.04, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.16, threshold: 0.16, mode: 'pulse', source: 'full' },
        shake: { amount: 0.24, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.3, threshold: 0.04, mode: 'normal', source: 'mid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.28, 0.36, 'low', 'normal', 0.07),
        1: layerLinks(0.24, 0.32, 'mid', 'normal', 0.08),
        2: layerLinks(0.2, 0.28, 'presence', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.34, timelineAmount: 0.22, scaleAmount: 0.18 }),
        1: makeMotion({ speedAmount: 0.28, timelineAmount: 0.2, scaleAmount: 0.16 }),
        2: makeMotion({ speedAmount: 0.22, timelineAmount: 0.16, scaleAmount: 0.12 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'medium',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 60,
      beatSyncEnabled: false,
    },
  },
  {
    id: 'fracture-step',
    name: 'Fracture Step',
    description: 'Broken rhythm scene with syncopated pulse triggers.',
    settings: {
      bpm: 138,
      audioSensitivity: 0.9,
      audioSmoothing: 0.34,
      audioNoiseFloor: 0.026,
      audioPreGain: 1.68,
      audioEq: { low: 1.16, mid: 1.14, high: 1.0 },
      masterFx: { glow: 0.24, strobe: 0.28, shake: 0.3, brightness: 1.04, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.34, threshold: 0.05, mode: 'normal', source: 'mid' },
        strobe: { amount: 0.44, threshold: 0.11, mode: 'pulse', source: 'full' },
        shake: { amount: 0.48, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.18, threshold: 0.07, mode: 'pulse', source: 'high' },
      },
      layerAudioLinks: {
        0: layerLinks(0.4, 0.7, 'full', 'pulse', 0.09),
        1: layerLinks(0.34, 0.58, 'mid', 'pulse', 0.1),
        2: layerLinks(0.28, 0.48, 'high', 'pulse', 0.11),
      },
      layerVideoMotion: {
        0: makeMotion({ bounceEnabled: true, bounceSpeed: 1.2, speedAmount: 0.64, timelineAmount: 0.52, timelineMode: 'pulse', scaleAmount: 0.28 }),
        1: makeMotion({ bounceEnabled: true, bounceSpeed: 1.14, speedAmount: 0.54, timelineAmount: 0.44, timelineMode: 'pulse', scaleAmount: 0.22 }),
        2: makeMotion({ bounceEnabled: true, bounceSpeed: 1.1, speedAmount: 0.44, timelineAmount: 0.36, timelineMode: 'pulse', scaleAmount: 0.18 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: true,
      dropThresholdLevel: 'low',
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 28,
      beatSyncEnabled: true,
    },
  },
  {
    id: 'deep-wave',
    name: 'Deep Wave',
    description: 'Low-mid rolling scene for deep house style pacing.',
    settings: {
      bpm: 122,
      audioSensitivity: 0.74,
      audioSmoothing: 0.56,
      audioNoiseFloor: 0.018,
      audioPreGain: 1.28,
      audioEq: { low: 1.12, mid: 1.0, high: 0.9 },
      masterFx: { glow: 0.22, strobe: 0.06, shake: 0.12, brightness: 1.12, kaleido: 0, kaleidoSegments: 6, kaleidoSpin: 0, kaleidoAudio: 0.5, kaleidoSource: 'mid' },
      audioFxLinks: {
        glow: { amount: 0.32, threshold: 0.04, mode: 'normal', source: 'lowMid' },
        strobe: { amount: 0.1, threshold: 0.19, mode: 'pulse', source: 'sub' },
        shake: { amount: 0.18, threshold: 0.08, mode: 'normal', source: 'low' },
        brightness: { amount: 0.28, threshold: 0.04, mode: 'normal', source: 'lowMid' },
      },
      layerAudioLinks: {
        0: layerLinks(0.24, 0.3, 'lowMid', 'normal', 0.07),
        1: layerLinks(0.2, 0.26, 'low', 'normal', 0.08),
        2: layerLinks(0.16, 0.22, 'mid', 'normal', 0.09),
      },
      layerVideoMotion: {
        0: makeMotion({ speedAmount: 0.3, timelineAmount: 0.2, scaleAmount: 0.16 }),
        1: makeMotion({ speedAmount: 0.24, timelineAmount: 0.16, scaleAmount: 0.13 }),
        2: makeMotion({ speedAmount: 0.2, timelineAmount: 0.14, scaleAmount: 0.1 }),
      },
      energySystemEnabled: true,
      dropSystemEnabled: false,
      clipVariationEnabled: true,
      autoEvolutionEnabled: true,
      autoEvolutionInterval: 85,
      beatSyncEnabled: false,
    },
  },
]
